{*********************************************************}
(*                B-Tree Filer Ver 5.55                  *)
{*     Copyright (c) TurboPower Software Co 1986-99      *}
{*                 All rights reserved.                  *}
(*      Based in part on code written by Ralf Nagel      *)
{*********************************************************}

Program OPISDemo;


{$I OPDefine.INC}
{$B-,S-,R-,V-,X+}

Uses
  OPISMain;

Begin
  Main;
End.

