  Caption:= MsgCaption(530);

  chkSrcTC.Caption:= MsgCaption(531);
  chkSrcFolder.Caption:= MsgCaption(532);
  chkSrcFile.Caption:= MsgCaption(533);
  chkSrcZip.Caption:= MsgCaption(534);
  labSource2.Caption:= MsgCaption(537);

  MsgViewerPluginsLabelTCIni:= MsgCaption(538);
  MsgViewerPluginsLabelFile:= MsgCaption(539);
  MsgViewerPluginsLabelFolder:= MsgCaption(540);
  MsgViewerPluginsFilterExe:= MsgCaption(541);
  MsgViewerPluginsFilterIni:= MsgCaption(542);
  MsgViewerPluginsFilterWLX:= MsgCaption(543);
  MsgViewerPluginsFilterZip:= MsgCaption(544);

  btnOk.Caption:= MsgCaption(350);
  btnCancel.Caption:= MsgCaption(351);
