  Caption:= MsgCaption(420);

  boxOptions.Caption:= ' ' + MsgCaption(428) + ' ';
  boxDirection.Caption:= ' ' + MsgCaption(429) + ' ';
  boxOrigin.Caption:= ' ' + MsgCaption(432) + ' ';

  labFind.Caption:= MsgCaption(421);
  chkWords.Caption:= MsgCaption(422);
  chkCase.Caption:= MsgCaption(423);
  chkHex.Caption:= MsgCaption(425);
  chkRegex.Caption:= MsgCaption(426) {$IFNDEF REGEX} + MsgCaption(427) {$ENDIF};
  chkMLine.Caption:= MsgCaption(424);
  chkDirForward.Caption:= MsgCaption(430);
  chkDirBackward.Caption:= MsgCaption(431);
  chkOriginCursor.Caption:= MsgCaption(434);
  chkOriginEntire.Caption:= MsgCaption(435);

  btnOk.Caption:= MsgCaption(352);
  btnCancel.Caption:= MsgCaption(351);
  btnHelp.Caption:= MsgCaption(155);
