{*********************************************************}
{* FlashFiler: Server component error codes              *}
{*********************************************************}

(* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is TurboPower FlashFiler
 *
 * The Initial Developer of the Original Code is
 * TurboPower Software
 *
 * Portions created by the Initial Developer are Copyright (C) 1996-2002
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *
 * ***** END LICENSE BLOCK ***** *)

{Note: Actual string values are found in the resource scripts
         FFLLSCST.STR - Server component error strings}

{String constants}
const
  ffsce_NoErrorCode = $500;
  ffsce_HasErrorCode = $501;
  ffsce_NilPointer = $502;
  ffsce_UnnamedInst = $503;
  ffsce_InstNoCode = $504;
  ffsce_MustBeInactive = $505;
  ffsce_MustBeStarted = $506;
  ffsce_MustBeListener = $507;
  ffsce_MustBeSender = $508;
  ffsce_MustHaveServerName = $509;
  ffsce_ParameterRequired = $50A;
  
