{----------------------------------------------------------------}
{                                                                }
{  Degisy Data Access Unit                                       }
{  Writen by Alexander Momot                                     }
{  http://www.degisy.com                                         }
{  (c)2001-2004 Degisy Software                                  }
{                                                                }
{----------------------------------------------------------------}
{-$DEFINE TRIAL_VERSION}

{$IFDEF VER100}  { Delphi 3 }
  {$DEFINE VCL3}
  {$DEFINE DELPHI3}
{$ENDIF}

{$IFDEF VER110}  { C++Builder 3 }
  {$DEFINE VCL3}
  {$DEFINE CBUILDER3}
{$ENDIF}

{$IFDEF VER120}  { Delphi 4 }
  {$DEFINE VCL4}
{$ENDIF}

{$IFDEF VER125}  { C++Builder 4 }
  {$DEFINE VCL4}
{$ENDIF}

{$IFDEF VER130}  { Delphi 5 }
  {$DEFINE VCL4}
  {$DEFINE VCL5}
{$ENDIF}

{$IFDEF VER135}  { C++Builder 5 }
  {$DEFINE VCL4}
  {$DEFINE VCL5}
{$ENDIF}

{$IFDEF VER140}  { Delphi 6 }
  {$DEFINE VCL4}
  {$DEFINE VCL5}
  {$DEFINE VCL6}
{$ENDIF}

{$IFDEF VER145}  { C++Builder 6 }
  {$DEFINE VCL4}
  {$DEFINE VCL5}
  {$DEFINE VCL6}
{$ENDIF}

{$IFDEF VER150}  { Delphi 7 }
  {$DEFINE VCL4}
  {$DEFINE VCL5}
  {$DEFINE VCL6}
  {$DEFINE VCL7}
{$ENDIF}
