unit IFSI_cakdir2cmd;
{
This file has been generated by UnitParser v0.5, written by M. Knight
and updated by NP. v/d Spek.
Source Code from Carlo Kok has been used to implement various sections of
UnitParser. Components of ifps3 are used in the construction of UnitParser,
code implementing the class wrapper is taken from Carlo Kok''s conv unility

}

{$I ifps3_def.inc}
interface
 
uses
   SysUtils
  ,Classes
  ,IFPS3CompExec
  ,ifpscomp
  ,ifps3
  ;
 
type 
(*----------------------------------------------------------------------------*)
  TIFPS3CE_cakdir2cmd = class(TIFPS3Plugin)
  protected
    procedure CompOnUses(CompExec: TIFPS3CompExec); override;
    procedure ExecOnUses(CompExec: TIFPS3CompExec); override;
    procedure CompileImport1(CompExec: TIFPS3CompExec); override;
    procedure CompileImport2(CompExec: TIFPS3CompExec); override;
    procedure ExecImport1(CompExec: TIFPS3CompExec; const ri: TIFPSRuntimeClassImporter); override;
    procedure ExecImport2(CompExec: TIFPS3CompExec; const ri: TIFPSRuntimeClassImporter); override;
  end;
 
 

{ compile-time registration functions }
procedure SIRegister_cakdir2cmd(CL: TIFPSPascalCompiler);

{ run-time registration functions }
procedure RIRegister_cakdir2cmd_Routines(S: TIFPSExec);



implementation


uses
   Windows
  ,Dialogs
  ,Cakdir2
  ,Forms
  ,QzRegistry
  ,StdCtrls
  ,PBFolderDialog
  ,cakdir2cmd
  ;
 
 
{ compile-time importer function }
(*----------------------------------------------------------------------------
 Sometimes the CL.AddClassN() fails to correctly register a class, 
 for unknown (at least to me) reasons
 So, you may use the below RegClassS() replacing the CL.AddClassN()
 of the various SIRegister_XXXX calls 
 ----------------------------------------------------------------------------*)
function RegClassS(CL: TIFPSPascalCompiler; const InheritsFrom, Classname: string): TIFPSCompileTimeClass;
begin
  Result := CL.FindClass(Classname);
  if Result = nil then
    Result := CL.AddClassN(CL.FindClass(InheritsFrom), Classname)
  else Result.ClassInheritsFrom := CL.FindClass(InheritsFrom);
end;
  
  
(* === compile-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure SIRegister_cakdir2cmd(CL: TIFPSPascalCompiler);
begin
 CL.AddType('TSearchRec',TSearchRec);
 CL.AddDelphiFunction('Function Param : Tstrings');
 CL.AddDelphiFunction('Procedure New( name : string)');
 CL.AddDelphiFunction('Procedure Open( name : string)');
 CL.AddDelphiFunction('Procedure Close');
 CL.AddDelphiFunction('Procedure Test');
 CL.AddDelphiFunction('Procedure Extract( what, too : string)');
 CL.AddDelphiFunction('Procedure Add( what : string)');
 CL.AddDelphiFunction('Procedure DoAdd');
 CL.AddDelphiFunction('Procedure Del( what : string)');
 CL.AddDelphiFunction('Procedure Ren( what, too : string)');
 CL.AddDelphiFunction('Procedure Convert( what, totype : string)');
 CL.AddDelphiFunction('Procedure Password( what : string)');
 CL.AddDelphiFunction('Procedure Useextrpath( toggle : boolean)');
 CL.AddDelphiFunction('Procedure Useextroverwrite( toggle : boolean)');
 CL.AddDelphiFunction('Procedure Useaddpath( toggle : boolean)');
 CL.AddDelphiFunction('Procedure UseVerCtrl( toggle : boolean)');
 CL.AddDelphiFunction('Procedure Userelativepath( toggle : boolean)');
 CL.AddDelphiFunction('Procedure Usesubdir( toggle : boolean)');
 CL.AddDelphiFunction('Procedure RunFile( what : string)');
 CL.AddDelphiFunction('Procedure MoveFile( what, too : string)');
 CL.AddDelphiFunction('Procedure RenFile( what, too : string)');
 CL.AddDelphiFunction('Procedure DelFile( what : string)');
 CL.AddDelphiFunction('Procedure CopyFile( what, too : string)');
 CL.AddDelphiFunction('Procedure MakeDir( what : string)');
 CL.AddDelphiFunction('Procedure DelDir( what : string)');
 CL.AddDelphiFunction('Procedure OpenFolder( what : string)');
 CL.AddDelphiFunction('Procedure Sort( index : integer; accending : boolean)');
 CL.AddDelphiFunction('Function Total_Contents : integer');
 CL.AddDelphiFunction('Function Contents_Filename( which : integer) : String');
 CL.AddDelphiFunction('Function Contents_FileDefPath( which : integer) : String');
 CL.AddDelphiFunction('Function Contents_FileSize( which : integer) : Integer');
 CL.AddDelphiFunction('Function Contents_FileCompSize( which : integer) : Integer');
 CL.AddDelphiFunction('Function Contents_FileSelected( which : integer) : Boolean');
 CL.AddDelphiFunction('Function Contents_FileType( which : integer) : String');
 CL.AddDelphiFunction('Function Contents_FileDateTime( which : integer) : TDatetime');
 CL.AddDelphiFunction('Procedure Select_File( which : integer)');
 CL.AddDelphiFunction('Procedure DeSelect_File( which : integer)');
 CL.AddDelphiFunction('Function Mask_Select_File( mask : string) : integer');
 CL.AddDelphiFunction('Procedure Clear_select');
 CL.AddDelphiFunction('Function TempPath : String');
 CL.AddDelphiFunction('Function MydocuPath : string');
 CL.AddDelphiFunction('Function DesktopPath : string');
 CL.AddDelphiFunction('Function SystemPath : string');
 CL.AddDelphiFunction('Function GetFileSize( const FileName : String) : Integer');
 CL.AddDelphiFunction('Function GetFileDateTime( const FileName : String) : TDatetime');
 CL.AddDelphiFunction('Function appendSlash( input : string) : string');
 CL.AddDelphiFunction('Function pollfilelist( maskedname : string; subdir : boolean) : tstrings');
 CL.AddDelphiFunction('Function New_Form( Left, Top, Width, Height : integer; Caption : string) : TForm');
 CL.AddDelphiFunction('Function New_Label( Form : TForm; Left, Top : integer; Caption : String) : TLabel');
 CL.AddDelphiFunction('Function New_Edit( Form : TForm; Left, Top, Width, Height : integer; Text : String) : TEdit');
 CL.AddDelphiFunction('Function New_Button( Form : TForm; Left, Top, Width, Height : integer; Caption : String) : TButton');
 CL.AddDelphiFunction('Function New_Memo( Form : TForm; Left, Top, Width, Height : integer) : TMemo');
 CL.AddDelphiFunction('Function AskDirDialog( Default : String) : String');
 CL.AddDelphiFunction('Function AskFilenameDialog( Default, filter : String) : String');
 CL.AddDelphiFunction('Procedure Show_Form( aForm : TForm)');
 CL.AddDelphiFunction('function FileExists(const FileName: string): Boolean;');
 CL.AddDelphiFunction('function ChangeFileExt(const FileName, Extension: string): string;');

 CL.AddDelphiFunction('function CreateDir(const Dir: string): Boolean;');
 CL.AddDelphiFunction('function DateTimeToStr(DateTime: TDateTime): string;');
 CL.AddDelphiFunction('function DeleteFile(const FileName: string): Boolean;');
 CL.AddDelphiFunction('function DirectoryExists(const Directory: string): Boolean;');
 CL.AddDelphiFunction('function DiskFree(Drive: Byte): Int64;');
 CL.AddDelphiFunction('function DiskSize(Drive: Byte): Int64;');
 CL.AddDelphiFunction('function EncodeDate(Year, Month, Day: Word): TDateTime;');
 CL.AddDelphiFunction('function ExpandFileName(const FileName: string): string;');
 CL.AddDelphiFunction('function ExtractFileName(const FileName: string): string;');
 CL.AddDelphiFunction('function ExtractFilePath(const FileName: string): string;');
 CL.AddDelphiFunction('function FindFirst(const Path: string; Attr: Integer; var F: TSearchRec): Integer;');
 CL.AddDelphiFunction('function FindNext(var F: TSearchRec): Integer;');
 CL.AddDelphiFunction('function RenameFile(const OldName, NewName: string): Boolean;');


end;

(* === run-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure RIRegister_cakdir2cmd_Routines(S: TIFPSExec);
begin
 S.RegisterDelphiFunction(@Param, 'Param', cdRegister);
 S.RegisterDelphiFunction(@New, 'New', cdRegister);
 S.RegisterDelphiFunction(@Open, 'Open', cdRegister);
 S.RegisterDelphiFunction(@Close, 'Close', cdRegister);
 S.RegisterDelphiFunction(@Test, 'Test', cdRegister);
 S.RegisterDelphiFunction(@Extract, 'Extract', cdRegister);
 S.RegisterDelphiFunction(@Add, 'Add', cdRegister);
 S.RegisterDelphiFunction(@DoAdd, 'DoAdd', cdRegister);
 S.RegisterDelphiFunction(@Del, 'Del', cdRegister);
 S.RegisterDelphiFunction(@Ren, 'Ren', cdRegister);
 S.RegisterDelphiFunction(@Convert, 'Convert', cdRegister);
 S.RegisterDelphiFunction(@Password, 'Password', cdRegister);
 S.RegisterDelphiFunction(@Useextrpath, 'Useextrpath', cdRegister);
 S.RegisterDelphiFunction(@Useextroverwrite, 'Useextroverwrite', cdRegister);
 S.RegisterDelphiFunction(@Useaddpath, 'Useaddpath', cdRegister);
 S.RegisterDelphiFunction(@UseVerCtrl, 'UseVerCtrl', cdRegister);
 S.RegisterDelphiFunction(@Userelativepath, 'Userelativepath', cdRegister);
 S.RegisterDelphiFunction(@Usesubdir, 'Usesubdir', cdRegister);
 S.RegisterDelphiFunction(@RunFile, 'RunFile', cdRegister);
 S.RegisterDelphiFunction(@MoveFile, 'MoveFile', cdRegister);
 S.RegisterDelphiFunction(@RenFile, 'RenFile', cdRegister);
 S.RegisterDelphiFunction(@DelFile, 'DelFile', cdRegister);
 S.RegisterDelphiFunction(@CopyFile, 'CopyFile', cdRegister);
 S.RegisterDelphiFunction(@MakeDir, 'MakeDir', cdRegister);
 S.RegisterDelphiFunction(@DelDir, 'DelDir', cdRegister);
 S.RegisterDelphiFunction(@OpenFolder, 'OpenFolder', cdRegister);
 S.RegisterDelphiFunction(@Sort, 'Sort', cdRegister);
 S.RegisterDelphiFunction(@Total_Contents, 'Total_Contents', cdRegister);
 S.RegisterDelphiFunction(@Contents_Filename, 'Contents_Filename', cdRegister);
 S.RegisterDelphiFunction(@Contents_FileDefPath, 'Contents_FileDefPath', cdRegister);
 S.RegisterDelphiFunction(@Contents_FileSize, 'Contents_FileSize', cdRegister);
 S.RegisterDelphiFunction(@Contents_FileCompSize, 'Contents_FileCompSize', cdRegister);
 S.RegisterDelphiFunction(@Contents_FileSelected, 'Contents_FileSelected', cdRegister);
 S.RegisterDelphiFunction(@Contents_FileType, 'Contents_FileType', cdRegister);
 S.RegisterDelphiFunction(@Contents_FileDateTime, 'Contents_FileDateTime', cdRegister);
 S.RegisterDelphiFunction(@Select_File, 'Select_File', cdRegister);
 S.RegisterDelphiFunction(@DeSelect_File, 'DeSelect_File', cdRegister);
 S.RegisterDelphiFunction(@Mask_Select_File, 'Mask_Select_File', cdRegister);
 S.RegisterDelphiFunction(@Clear_select, 'Clear_select', cdRegister);
 S.RegisterDelphiFunction(@TempPath, 'TempPath', cdRegister);
 S.RegisterDelphiFunction(@MydocuPath, 'MydocuPath', cdRegister);
 S.RegisterDelphiFunction(@DesktopPath, 'DesktopPath', cdRegister);
 S.RegisterDelphiFunction(@SystemPath, 'SystemPath', cdRegister);
 S.RegisterDelphiFunction(@GetFileSize, 'GetFileSize', cdRegister);
 S.RegisterDelphiFunction(@GetFileDateTime, 'GetFileDateTime', cdRegister);
 S.RegisterDelphiFunction(@appendSlash, 'appendSlash', cdRegister);
 S.RegisterDelphiFunction(@pollfilelist, 'pollfilelist', cdRegister);
 S.RegisterDelphiFunction(@New_Form, 'New_Form', cdRegister);
 S.RegisterDelphiFunction(@New_Label, 'New_Label', cdRegister);
 S.RegisterDelphiFunction(@New_Edit, 'New_Edit', cdRegister);
 S.RegisterDelphiFunction(@New_Button, 'New_Button', cdRegister);
 S.RegisterDelphiFunction(@New_Memo, 'New_Memo', cdRegister);
 S.RegisterDelphiFunction(@AskDirDialog, 'AskDirDialog', cdRegister);
 S.RegisterDelphiFunction(@AskFilenameDialog, 'AskFilenameDialog', cdRegister);
 S.RegisterDelphiFunction(@Show_Form, 'Show_Form', cdRegister);
 S.RegisterDelphiFunction(@Sysutils.FileExists, 'FileExists', cdRegister);
 S.RegisterDelphiFunction(@Sysutils.ChangeFileExt, 'ChangeFileExt', cdRegister);
 S.RegisterDelphiFunction(@Sysutils.DateTimeToStr, 'DateTimeToStr', cdRegister);
 S.RegisterDelphiFunction(@Sysutils.DeleteFile, 'DeleteFile', cdRegister);
 S.RegisterDelphiFunction(@Sysutils.DirectoryExists, 'DirectoryExists', cdRegister);
 S.RegisterDelphiFunction(@Sysutils.DiskFree, 'DiskFree', cdRegister);
 S.RegisterDelphiFunction(@Sysutils.DiskSize, 'DiskSize', cdRegister);
 S.RegisterDelphiFunction(@Sysutils.EncodeDate, 'EncodeDate', cdRegister);
 S.RegisterDelphiFunction(@Sysutils.ExpandFileName, 'ExpandFileName', cdRegister);
 S.RegisterDelphiFunction(@Sysutils.ExtractFileName, 'ExtractFileName', cdRegister);
 S.RegisterDelphiFunction(@Sysutils.ExtractFilePath, 'ExtractFilePath', cdRegister);
 S.RegisterDelphiFunction(@Sysutils.FindFirst, 'FindFirst', cdRegister);
 S.RegisterDelphiFunction(@Sysutils.FindNext, 'FindNext', cdRegister);
 S.RegisterDelphiFunction(@Sysutils.RenameFile, 'RenameFile', cdRegister);
end;

 
 
{ TIFPS3CE_cakdir2cmd }
(*----------------------------------------------------------------------------*)
procedure TIFPS3CE_cakdir2cmd.CompOnUses(CompExec: TIFPS3CompExec);
begin
  { nothing } 
end;
(*----------------------------------------------------------------------------*)
procedure TIFPS3CE_cakdir2cmd.ExecOnUses(CompExec: TIFPS3CompExec);
begin
  { nothing }
end;
(*----------------------------------------------------------------------------*)
procedure TIFPS3CE_cakdir2cmd.CompileImport1(CompExec: TIFPS3CompExec);
begin
  SIRegister_cakdir2cmd(CompExec.Comp);
end;
(*----------------------------------------------------------------------------*)
procedure TIFPS3CE_cakdir2cmd.CompileImport2(CompExec: TIFPS3CompExec);
begin
  { nothing } 
end;
(*----------------------------------------------------------------------------*)
procedure TIFPS3CE_cakdir2cmd.ExecImport1(CompExec: TIFPS3CompExec; const ri: TIFPSRuntimeClassImporter);
begin
  //RIRegister_cakdir2cmd(ri);
  //RIRegister_cakdir2cmd_Routines(CompExec.Exec); // comment it if no routines
end;
(*----------------------------------------------------------------------------*)
procedure TIFPS3CE_cakdir2cmd.ExecImport2(CompExec: TIFPS3CompExec; const ri: TIFPSRuntimeClassImporter);
begin
  { nothing } 
end;
 
 
initialization
 (**)
{$IFDEF USEIMPORTER}
CIImporter.AddCallBack(@SIRegister_cakdir2cmd,PT_ClassImport);
{$ENDIF}
finalization
 (**) 
 
end.
