const //Exception messages
  sfbeOtherError          = 'Other error';
  sfbeCircularReference   = 'The cyclic reference a component is forbidden (%s).'; //fbeCircularReference
  sfbeEmptySQLEdit        = 'Empty edit SQL statament (%s).'; //sfbeEmptySQLEdit
  sfbeDatabaseNotAssigned = 'Database not assigned (%s)';
  sfbeTransactionNotAssigned = 'Transaction not assigned (%s)';
  sfbeParameterNotFound   = 'Parameter not found (%s)';
  sfbeNotCachedUpdates    = 'Not Cached Updates (%s)';
  sfbeUserAbort           = 'User abort';
  sfbeErrorExecuteQ       = 'Error execute query %s (%s).';
  sfbeBlobCannotBeWritten = 'Blob stream cannot be written.';
  sfbeCannotInsert        = 'Cannot Insert %s.';
  sfbeGetRecordInvalidRec = 'GetRecord: Invalid record';

  EReferencedRecordBufferLooseMsg = 'try to free referenced record buffer';
  EReferencedDatSetRecordBufferLooseMsg = 'try to free referenced DatSet record buffer';
  EReferencedBLOBCacheLooseMsg    = 'TBLOBCache:try to destroy used cache';

const //Localizations
  slcOk     = 'OK';
  slcCancel = 'Cancel';
  slcHelp   = 'Help';
  //Auto update options window
  slcUpdatedField  = 'Updated field';
  slcGeneratorName = 'Generator name';
  slcIncrementBy   = 'Increment by';
