CREATE TABLE mytab (
  id  NUMBER(10) NULL,
  txt CHAR(10)   NULL
);

CREATE OR REPLACE PROCEDURE INS_(ID_ NUMBER, TXT_ CHAR) IS
BEGIN
	INSERT INTO mytab VALUES (ID_, TXT_);
END INS_;
/

CREATE OR REPLACE PROCEDURE UPD_(ID_ NUMBER, TXT_ CHAR) IS
BEGIN
	UPDATE mytab SET TXT=TXT_ WHERE ID=ID_;
END UPD_;
/

CREATE OR REPLACE PROCEDURE DEL_(ID_ NUMBER) IS
BEGIN
	DELETE FROM mytab WHERE ID=ID_;
END DEL_;
/