{*********************************************************}
{* FlashFiler: Stringtable constants for DataSet code    *}
{*********************************************************}

(* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is TurboPower FlashFiler
 *
 * The Initial Developer of the Original Code is
 * TurboPower Software
 *
 * Portions created by the Initial Developer are Copyright (C) 1996-2002
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *
 * ***** END LICENSE BLOCK ***** *)

{Note: Actual string values are found in the resource scripts
         FFDSCNST.STR - TDataSet descendant strings}

{String constants}
Const
  fsdse_NoErrorCode = $D500;
  fsdse_HasErrorCode = $D501;
  fsdse_NilPointer = $D502;
  fsdse_UnnamedInst = $D503;
  fsdse_InstNoCode = $D504;
  fsdse_MissingItem = $D505;
  fsdse_MustBeClosed = $D506;
  fsdse_MustBeOpen = $D507;
  fsdse_MissingOwner = $D508;
  fsdse_NeedsName = $D509;
  fsdse_NeedsOwnerName = $D50A;
  fsdse_NoDefaultCL = $D50B;
  fsdse_NoSessions = $D50C;
  fsdse_NilSession = $D50D;
  fsdse_CLNameExists = $D50E;
  fsdse_CLMustBeOpen = $D50F;
  fsdse_CLMustBeClosed = $D510;
  fsdse_SessMustBeOpen = $D511;
  fsdse_SessMustBeClosed = $D512;
  fsdse_CannotStartEng = $D513;
  fsdse_CannotStartCL = $D514;
  fsdse_CannotOpenSess = $D515;
  fsdse_SessNameExists = $D516;
  fsdse_DBMustBeClosed = $D517;
  fsdse_DBMustBeOpen = $D518;
  fsdse_CantOpenDBSess = $D519;
  fsdse_DBNoOwningSess = $D51A;
  fsdse_MatchesAlias = $D51B;
  fsdse_DBNameExists = $D51C;
  fsdse_TblMustBeClosed = $D51D;
  fsdse_TblMustBeOpen = $D51E;
  fsdse_CantOpenTblDB = $D51F;
  fsdse_NotSameTbl = $D520;
  fsdse_UnnamedTblNoFlds = $D521;
  fsdse_CantGetTblHandle = $D522;
  fsdse_TblNotEditing = $D523;
  fsdse_TblFldNotInIndex = $D524;
  fsdse_TblCantGetBuf = $D525;
  fsdse_TblCalcFlds = $D526;
  fsdse_TblReadOnlyEdit = $D527;
  fsdse_TblChkKeyNoEdit = $D528;
  fsdse_TblNoName = $D529;
  fsdse_TblBadDBName = $D52A;
  fsdse_TblBadDBRefCount = $D52B;
  fsdse_TblBadReadOnly = $D52C;
  fsdse_TblIdxFldRange = $D52D;
  fsdse_TblIdxFldMissing = $D52E;
  fsdse_TblIdxNotExist = $D52F;
  fsdse_TblCircDataLink = $D530;
  fsdse_BLOBFltNoFldAccess = $D531;
  fsdse_BLOBAccessNoMatch = $D532;
  fsdse_BLOBTblNoEdit = $D533;
  fsdse_InvalidFieldType = $D534;
  fsdse_InstCode = $D535;
  fsdse_EmptySQLStatement = $D536;
  fsdse_QueryMustBeClosed = $D537;
  fsdse_QueryExecFail = $D538;
  fsdse_QuerySetParamsFail = $D539;
  fsdse_QueryPrepareFail = $D53A;
  fsdse_RSENeedsTransport = $D53B;
  fsdse_StartTranTblActive = $D53C; {!!.10}

