//---------------------------------------------------------------------------
#include <vcl.h>
#pragma hdrstop
USERES("fsql1_r_bcb51.res");
USEUNIT("fssrsort.pas");
USEUNIT("fssrcur.pas");
USEUNIT("fsllcoll.pas");
USEUNIT("fscocobase.pas");
USEUNIT("fsclbase.pas");
USEUNIT("fsclbde.pas");
USEUNIT("fsclcfg.pas");
USEUNIT("fsclconv.pas");
USEUNIT("fsclintf.pas");
USEUNIT("fsserverremoteclass.pas");
USEUNIT("fscltbrg.pas");
USEUNIT("fsdb.pas");
USEUNIT("fsfile.pas");
USEUNIT("fshash.pas");
USEUNIT("fsllbase.pas");
USEUNIT("fsllcomm.pas");
USEUNIT("fsllcomp.pas");
USEUNIT("fslldict.pas");
USEUNIT("fslleng.pas");
USEUNIT("fsllexcp.pas");
USEUNIT("fsllgrid.pas");
USEUNIT("fsconst.pas");
USEUNIT("fsconvff.pas");
USEUNIT("fsdbbase.pas");
USEUNIT("fsdtmsgq.pas");
USEUNIT("fslllgcy.pas");
USEUNIT("fslllog.pas");
USEUNIT("fsllprot.pas");
USEUNIT("fsllreq.pas");
USEUNIT("fsllthrd.pas");
USEUNIT("fsllunc.pas");
USEUNIT("fsllwsck.pas");
USEUNIT("fsllwsct.pas");
USEUNIT("fsnetmsg.pas");
USEUNIT("fssql.pas");
USEUNIT("fssqlbas.pas");
USEUNIT("fssqldb.pas");
USEUNIT("fssqldef.pas");
USEUNIT("fssqleng.pas");
USEUNIT("fssrbase.pas");
USEUNIT("fssrbde.pas");
USEUNIT("fssrblob.pas");
USEUNIT("fssrcfg.pas");
USEUNIT("fssrcmd.pas");
USEUNIT("fssrcvex.pas");
USEUNIT("fsserverclass.pas");
USEUNIT("fssrfltr.pas");
USEUNIT("fssrfmap.pas");
USEUNIT("fssrfold.pas");
USEUNIT("fssrintf.pas");
USEUNIT("fssrintm.pas");
USEUNIT("fsindexhelper.pas");
USEUNIT("fssrlock.pas");
USEUNIT("fssrmgr.pas");
USEUNIT("fssrsec.pas");
USEUNIT("fssrstat.pas");
USEUNIT("fssrtran.pas");
USEUNIT("fsstdate.pas");
USEUNIT("fsutil.pas");
USEPACKAGE("vcl50.bpi");
USEPACKAGE("vcldb50.bpi");
USEUNIT("fssrjour.pas");
//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------
//   Package source.
//---------------------------------------------------------------------------
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
  return 1;
}
//---------------------------------------------------------------------------
