{*******************************************************}
{                                                       }
{       Delphi Visual Component Library                 }
{       Custom Forms Pack (CFPack)                      }
{                                                       }
{       Copyright (c) 1997-99 Sergey Orlik              }
{                                                       }
{     Written by:                                       }
{       Sergey Orlik                                    }
{       product manager                                 }
{       Russia, C.I.S. and Baltic States (former USSR)  }
{       Inprise Moscow office                           }
{       Internet:  sorlik@inprise.ru                    }
{       www.geocities.com/SiliconValley/Way/9006/       }
{                                                       }
{*******************************************************}

//======================================
// VCL Version Define

{$IFDEF VER125}  // CBuilder 4
      {$DEFINE VER_VCL4}
{$ENDIF}

{$IFDEF VER120}  // Delphi 4
      {$DEFINE VER_VCL4}
{$ENDIF}


{$IFDEF VER110}  // CBuilder 3
      {$DEFINE VER_VCL35}
{$ENDIF}

{$IFDEF VER100}  // Delphi 3
      {$DEFINE VER_VCL3}
{$ENDIF}


//======================================
// Language&IDE Define

{$IFDEF VER125}  // CBuilder 4
      {$DEFINE VER_CB}
{$ENDIF}

{$IFDEF VER120}  // Delphi 4
      {$DEFINE VER_D}
{$ENDIF}

{$IFDEF VER110}  // CBuilder 3
      {$DEFINE VER_CB}
{$ENDIF}

{$IFDEF VER100}  // Delphi 3
      {$DEFINE VER_D}
{$ENDIF}

