{$I SZCLibStubs.inc}

function _wsprintfA:integer; external 'user32.dll' name 'wsprintfA';
procedure RtlUnwind; external 'NtDll.dll' name 'RtlUnwind';


{$L 'OBJ\SQLite3_5_1.obj'}

{$L 'OBJ\is.obj'}
{$L 'OBJ\ftol.OBJ'}
{$L 'OBJ\gmtime.obj'}
{$L 'OBJ\ltoupper.obj'}
{$L 'OBJ\ltolower.obj'}
{$L 'OBJ\_ll.obj'}
{$L 'OBJ\_ftoul.OBJ'}
{$L 'OBJ\atol.obj'}
{$L 'OBJ\isctype.obj'}
{$L 'OBJ\tzdata.obj'}
{$L 'OBJ\timedata.obj'}
{$L 'OBJ\timefunc.obj'}
{$L 'OBJ\cupper.obj'}
{$L 'OBJ\clower.obj'}
{$L 'OBJ\clocale.obj'}
{$L 'OBJ\mbisspc.obj'}
{$L 'OBJ\bigctype.obj'}
{$L 'OBJ\_tzset.obj'}
{$L 'OBJ\timedata.obj'}
{$L 'OBJ\tzset.obj'}
{$L 'OBJ\getenv.obj'}
{$L 'OBJ\mbisalp.obj'}
{$L 'OBJ\mbisdgt.obj'}
{$L 'OBJ\mbsnbcpy.obj'}
{$L 'OBJ\setenvp.obj'}
{$L 'OBJ\mbsnbicm.obj'}
{$L 'OBJ\mbctype.obj'}
{$L 'OBJ\is.obj'}
{$L 'OBJ\globals.obj'}
{$L 'OBJ\errormsg.obj'}
{$L 'OBJ\globals.obj'}
{$L 'OBJ\mbsrchr.obj'}
{$L 'OBJ\ermsghlp.obj'}
{$L 'OBJ\exit.obj'}
{$L 'OBJ\patexit.obj'}
{$L 'OBJ\initexit.obj'}
{$L 'OBJ\globals.obj'}

