{

Translated by:

Guillermo CastaŸo
Grupo Millennium Ltda
www.grupomillennium.com

}
  SPSCPrmBoxEditor                              = 'Editar component...';
  SPSCOperationDispAnd                          = 'i';
  SPSCOperationDispOr                           = 'o';
  SPSCErrMemSlotDelete                          = 'No es pot esborrar aquesta Memòria';
  SPSCErrSystemSlot                             = 'No es pot desar en en aquesta Memòria';
  SPSCPrmBoxSaveToMem                           = '&Desar en la Memòria...';
  SPSCPrmBoxLoadFromMem                         = '&Carregar des de la Memòria...';
  SPSCClickHereToAddItem                        = '<Polseu aquí per afegir un element>';
  SPSCClickHereToAddCond                        = '<Polseu aquí per afegir una condició>';
  SPSCFltSaveFileCat                            = 'Filtres';
  SPSCListPopupAdd                              = '&Afegir';
  SPSCListPopupDelete                           = '&Esborrar';
  SPSCListPopupIndent                           = '&Indentar';
  SPSCListPopupOutDent                          = '&Desindentar';
  SPSCListPopupSave                             = '&Desar...';
  SPSCListPopupLoad                             = '&Obrir...';
  SPSCListPopupClear                            = '&Netejar';
  SPSCDeleteButton                              = 'Esborrar';
  SPSCCap_Cont                                  = 'conté';
  SPSCCap_Is                                    = 'és (exactament)';
  SPSCCap_NotCont                               = 'no conté';
  SPSCCap_IsEmpty                               = 'està buit';
  SPSCCap_IsNEmpty                              = 'no està buit';
  SPSCCap_Equals                                = 'és igual a';
  SPSCCap_NEquals                               = 'no és igual a';
  SPSCCap_AtMost                                = 'tot lo més';
  SPSCCap_AtLeast                               = 'al menys';
  SPSCCap_More                                  = 'major que';
  SPSCCap_Less                                  = 'menor que';
  SPSCCap_Between                               = 'entre';
  SPSCCap_Yesterday                             = 'va ser ~ahir~';
  SPSCCap_Today                                 = 'és ~avui~';
  SPSCCap_Tomorrow                              = 'serà ~demà~';
  SPSCCap_Last7                                 = 'estè dins els ~darrers 7 dies~';
  SPSCCap_Next7                                 = 'està dins els ~propers 7 dies~';
  SPSCCap_LastWeek                              = 'va ser la ~darrera setmana~';
  SPSCCap_ThisWeek                              = 'està dins ~aquesta setmana~';
  SPSCCap_NextWeek                              = 'estarà dins la ~propera setmana~';
  SPSCCap_LastMon                               = 'està dins el ~darrer mes~';
  SPSCCap_ThisMon                               = 'està dins ~aquest mes~';
  SPSCCap_NextMon                               = 'estarà en el ~proper mes~';
  SPSCCap_On                                    = 'està ~ara~';
  SPSCCap_OnAfter                               = 'està ~ara o després~';
  SPSCCap_Onbefore                              = 'està ~ara o abans~';
  SPSCCap_After                                 = 'després';
  SPSCCap_Before                                = 'abans';
  SPSCCap_BlankEmpty                            = 'està ~en blanc o buit~';
  SPSCtempl2                                    = ':Camp :Plantilla :Valor1 i :Valor2';
  SPSCUntitled                                  = 'sense titol';
  SPSCCalcError                                 = 'ERROR';
  SPSCErrCharPos                                = ' en la Línea:%d, Caràcter:%d. ';
  SPSCTokenListEmpty                            = 'La llista de d''elements està buida';
  SPSCErrFutureState                            = 'L''estat està en el futur';
  SPSCErrBadFilter                              = 'Filtre incorrecte.';
  SPSCBoolDispTrue                              = 'Vertader';
  SPSCBoolDispFalse                             = 'Fals';
  SPSCApplyButton                               = '&Aplicar';
  SPSCCap_Begins                                = 'comença amb';
  SPSCCap_Ends                                  = 'acaba amb';


  SPSCTodayButton           = '&Avui';
  SPSCNoneButton            = '&Cap';

  SPSCSelectMonth           = 'Seleccioneu un mes';
  SPSCDefaultString         = 'Defecte';
  SPSCHolEaster             = 'Oriental';
  SPSC_AHC_Label            = 'Seleccioneu els llocs els festius dels quals us agradaria copiar al calendari:';
  SPSC_AHC_AddHolidaysToCal = 'Afegir festius al calendari';
  SPSCPrintStatus           = 'Estat de la impressió';
  SPSCSearchPrinters        = 'Cercant impressores ...';
  SPSCPrintProgress         = 'Imprimint pàginas:    calculant ..';
  SPSCPrintingPage          = 'Imprimint pàgina %d de %s';
  SPSCPrintingOnPrinter     = 'Imprimint en la impressora %s';
  SPSCPageNoStr             = 'Pàgina %d de %d.';
  SPSCNowButton             = 'Ara';

  sPSCErrEmptyFilter                            = 'No es pot activar el filtre amb una condició buida';
  sPSCErrNoMatchRecord                          = 'No hi ha registres que verifiquen el criteri de recerca.';
  sPSCErrEndReached                             = 'S''ha arrivat al final de la taula sense trobar coincidències.';
  sPSCErrBeginReached                           = 'S''ha arrivat al principi de la taula sense trobar coincidències.';
  sPSCSearchFromBegin                           = ' Voleu continuar la recerca des de el principi de la taula?';
  sPSCSearchFromEnd                             = ' Voleu continuar la recerca des del final de la taula?';
  SPSCSpecifyFilter                             = 'Especifiqueu el filtre';
  SPSCFilterLabel                               = '&Filtre:';
  SPSCExcludeFilterLabel                        = '&Excloure filtre:';
  SPSCCap_OnDate                                = 'és ~la data~';
  SPSCBadFieldType                              = 'Tipous de camp incorrecte';
  SPSCErrDataSetNilNoFields                     = 'Taula indefinida i camps no especificats';
  SPSCErrNoFields                               = 'Propietat Fields no especificada';


// Error messages
SPSCInvalidColor='''%s'' és un valor de color incorrecte';
SPSCInvalidClass='No es pot acceptar ''%s''';

// Color names
SPSCBlack='Negre';
SPSCBrown='Café';
SPSCOliveGreen='Vert Oliva';
SPSCDarkGreen='Vert Fosc';
SPSCDarkTeal='Aiguamarina Fosc';
SPSCDarkBlue='Blau Fosc';
SPSCIndigo='Indigo';
SPSCGray80='Gris-80%';
SPSCDarkRed='Roig Fosc';
SPSCOrange='Taronja';
SPSCDarkYellow='Groc fosc';
SPSCGreen='Vert';
SPSCTeal='Aiguamarina';
SPSCBlue='Blau';
SPSCBlueGray='Blau-Gris';
SPSCGray50='Gris-50%';
SPSCRed='Roig';
SPSCLightOrange='Taronja Clar';
SPSCLime='Llima';
SPSCSeaGreen='Vert Mar';
SPSCAqua='Aigua';
SPSCLightBlue='Blau clar';
SPSCViolet='Violat';
SPSCGray40='Gris-40%';
SPSCPink='Rosat';
SPSCGold='Or';
SPSCYellow='Groc';
SPSCBrightGreen='Vert Brillant';
SPSCTurquoise='Turquesa';
SPSCSkyBlue='Blau Cel';
SPSCPlum='Plom';
SPSCGray25='Gris-25%';
SPSCRose='Rosa';
SPSCTan='Canyella';
SPSCLightYellow='Groc Clar';
SPSCLightGreen='Vert Clar';
SPSCLightTurquoise='Turquesa Clar';
SPSCPaleBlue='Blau Pàl·lid';
SPSCLavender='Lavanda';
SPSCWhite='Blanc';

// New system color names
SPSCHotLight='Llum Calenta';
SPSCGradientActiveCaption='Gradient de Títol Actiu';
SPSCGradientInactiveCaption='Gradient de Títol Inactiu';
SPSCTransparent='Color Transparent';

// Captions
SPSCMoreColorsCapt='&Més colors...';
SPSCMoreColors='Més colors';
SPSCAuto='Automàtic';
SPSCAutoColor='Color Automàtico';
SPSCNone='Cap';
SPSCNoHighLight='Sense Ressaltar';
SPSCStdColors='&Colors Estàndar:';
SPSCWindowsColors='Colors de &Windows:';
SPSCDocColors='Colors del &Document:';
SPSCFontColors='Colors de &Font:';
SPSCCustomColors='Colors &Personalitzats:';
SPSCCustomColorsCapt='Colors Personalitzats';

// Items
SPSCAddSlot='Afegir ítem';
SPSCDeleteSlot='Eliminar ítem';

// Sections
SPSCDefaultSection='Secció por Defecte';
SPSCColorSection='Secció de Color';
SPSCButtonSection='Secció de Botó';

// Popup window
SPSCDragBarHint='Arrossegueu per fer flotant aquest menú';

  SPSCErrCharSetDef='Definició de joc de caràcters incorrecte';
  SPSCErrMaxIfDefReached='Només %d nivells encadenats de directives del compilador estan permesos';
  SPSCErrCompilerDirective='Directiva incorrecta del compilador: "%s"';
  SPSCErrFileNotFound='Arxiu %S no trobat';
  sPSCDirectory  = 'Directori :  ';
  SPSCNotProcessedfiles = 'Arxius no processats:';
  SPSCErrStringsNotSet = 'Els textos no s''han especificat';

//------------------ Not yet localized

  SPSCErrProgramFailed='Error de programa amb codi (%d)';
  SPSCCharExpected = '''''%s'''' era esperat';
  SPSCSymbolExpected = '%s era esperat';
  SPSCErrUnkProp = 'La propietat no existeix';
  SPSCErrLoadFile = 'No es pot carregar %s';


  SPSCErrAssignFilterSource='Assigneu la propietat FilterSource anb TPSCFltBld';
  SPSCErrConnectDataSet='Connecteu el TDataSet o especifiqueu la propietat Fields';
  SPSCErrNoFilterSource='FilterSource no està assignat';
  SPSCErrCanNotDestroy='No es pot destruir aquest objecte';
  SPSCErrBadPropElem = 'Element incorrecte a la propietat: %s';
  SPSCThereAreNoItems='No hi ha ítems per mostrar en aquesta vista';
  SPSCClickHeretoChangeSortOrder='Polseu aquí per canviar l''ordenació';
  SPSCSortAscending='Ordenació Ascendent';
  SPSCSortDescending='Ordenació Descendent';
  SPSCClearSortOrder='Netejar ordenació';
  SPSCIgnoreCase='&Ignorar majúscules/minúscules';
  SPSCClickHereToAddValue='<Polseu aquí per afegir un valor>';
  SPSCCap_In='en';
  SPSCCap_NotIn='no en';
  SPSCAddAllFields='Afegir tots els Camps';
  SPSCAddAllFieldParams='Afegir tots els FieldParams';
  SPSCFindFirst='Cercar el primer';
  SPSCFindPrev='Cercar l''anterior';
  SPSCFindNext='Cercar el següent';
  SPSCFindLast='Cercar el darrer';
  SPSCColorIndicatedCells='Color indicat per les cel·les';
  SPSCFiltered='Filtrat';
  SPSCErrHandlerAlreadyExists='El Handler ja existeix';
  SPSCErrHandlerNotExists='El Handler no existeix';
  SPSCApplyChanges='Aplicar canvis';
  SPSCCancelChanges='Ignorar canvis';
  SPSCErrDupItem = 'No se pot inserir un ítem duplicat';

  SPSCAdditionalFilter='[Filtre Addicional]';
  SPSCAutoUpdate='Actualitzar Automàticament';

  SPSCAssignError                            = 'No se pot assignar un %s a un %s';
  SPSCOKButton                               = 'OK';
  SPSCCancelButton                           = 'Cancel·lar';
  SPSCHelpButton                             = '&Ajuda';
  SPSCReadError                              = 'Error llegint les dades';
  SPSCWriteError                             = 'Error escrivint les dades';

  SPSCErrRefCount='El comptador de referències de l''objecte és diferent de zero';
  SPSCExceptionIn='Excepció en %S';
  SPSCErrInvalidfieldkind='Tipus de camp incorrecte';
  SPSCOperationDispAndNot                    = 'i no';
  SPSCOperationDispOrNot                     = 'o no';
