{

Translated by:

Guillermo CastaŸo
Grupo Millennium Ltda
www.grupomillennium.com

}
  SPSCPrmBoxEditor                              = 'Editar componente...';
  SPSCOperationDispAnd                          = 'y';
  SPSCOperationDispOr                           = 'o';
  SPSCErrMemSlotDelete                          = 'No se puede borrar esta Memoria';
  SPSCErrSystemSlot                             = 'No se puede guardar en esta Memoria';
  SPSCPrmBoxSaveToMem                           = '&Guardar en la Memoria...';
  SPSCPrmBoxLoadFromMem                         = '&Cargar desde la Memoria...';
  SPSCClickHereToAddItem                        = '<Pulsar aquí para añadir un elemento>';
  SPSCClickHereToAddCond                        = '<Pulsar aquí para añadir una condición>';
  SPSCFltSaveFileCat                            = 'Filtros';
  SPSCListPopupAdd                              = '&Añadir';
  SPSCListPopupDelete                           = '&Borrar';
  SPSCListPopupIndent                           = '&Indentar';
  SPSCListPopupOutDent                          = '&Desindentar';
  SPSCListPopupSave                             = '&Guardar...';
  SPSCListPopupLoad                             = '&Abrir...';
  SPSCListPopupClear                            = '&Limpiar';
  SPSCDeleteButton                              = 'Borrar';
  SPSCCap_Cont                                  = 'contiene';
  SPSCCap_Is                                    = 'es (exactamente)';
  SPSCCap_NotCont                               = 'no contiene';
  SPSCCap_IsEmpty                               = 'está vacío';
  SPSCCap_IsNEmpty                              = 'no está vacío';
  SPSCCap_Equals                                = 'es igual a';
  SPSCCap_NEquals                               = 'no es igual a';
  SPSCCap_AtMost                                = 'a lo más';
  SPSCCap_AtLeast                               = 'al menos';
  SPSCCap_More                                  = 'mayor que';
  SPSCCap_Less                                  = 'menor que';
  SPSCCap_Between                               = 'entre';
  SPSCCap_Yesterday                             = 'fue ~ayer~';
  SPSCCap_Today                                 = 'es ~hoy~';
  SPSCCap_Tomorrow                              = 'será ~mañana~';
  SPSCCap_Last7                                 = 'está entre los ~últimos 7 dias~';
  SPSCCap_Next7                                 = 'está entre los ~próximos 7 dias~';
  SPSCCap_LastWeek                              = 'fue en la ~última semana~';
  SPSCCap_ThisWeek                              = 'está en ~esta semana~';
  SPSCCap_NextWeek                              = 'estará en la ~próxima semana~';
  SPSCCap_LastMon                               = 'está en el ~último mes~';
  SPSCCap_ThisMon                               = 'está en ~este mes~';
  SPSCCap_NextMon                               = 'estará en el ~próximo mes~';
  SPSCCap_On                                    = 'está ~sobre~';
  SPSCCap_OnAfter                               = 'está ~sobre o después~';
  SPSCCap_Onbefore                              = 'está ~sobre o antes~';
  SPSCCap_After                                 = 'después';
  SPSCCap_Before                                = 'antes';
  SPSCCap_BlankEmpty                            = 'está ~en blanco o vacío~';
  SPSCtempl2                                    = ':Campo :Plantilla :Valor1 y :Valor2';
  SPSCUntitled                                  = 'sin título';
  SPSCCalcError                                 = 'ERROR';
  SPSCErrCharPos                                = ' en la Línea:%d, Carácter:%d. ';
  SPSCTokenListEmpty                            = 'La lista de Tokens está vacía';
  SPSCErrFutureState                            = 'El estado está en el futuro';
  SPSCErrBadFilter                              = 'Filtro incorrecto.';
  SPSCBoolDispTrue                              = 'Verdadero';
  SPSCBoolDispFalse                             = 'Falso';
  SPSCApplyButton                               = '&Aplicar';
  SPSCCap_Begins                                = 'comienza con';
  SPSCCap_Ends                                  = 'finaliza con';


  SPSCTodayButton           = '&Hoy';
  SPSCNoneButton            = '&Ninguno';

  SPSCSelectMonth           = 'Seleccione un mes';
  SPSCDefaultString         = 'Defecto';
  SPSCHolEaster             = 'Oriental';
  SPSC_AHC_Label            = 'Seleccione los lugares cuyos festivos le gustaría copiar a su Calendario:';
  SPSC_AHC_AddHolidaysToCal = 'Adicionar festivos al Calendario';
  SPSCPrintStatus           = 'Estado de impresión';
  SPSCSearchPrinters        = 'Buscando impresoras ...';
  SPSCPrintProgress         = 'Imprimiento páginas:    calculando ..';
  SPSCPrintingPage          = 'Imprimiendo página %d de %s';
  SPSCPrintingOnPrinter     = 'Imprimiendo en impresora %s';
  SPSCPageNoStr             = 'Página %d de %d.';
  SPSCNowButton             = 'Ahora';

  sPSCErrEmptyFilter                            = 'No se puede activar el filtro con una condición vacía';
  sPSCErrNoMatchRecord                          = 'No hay registros que cumplan con el criterio de búsqueda.';
  sPSCErrEndReached                             = 'Se llegó al final de la tabla y no se encontraron registros coincidentes.';
  sPSCErrBeginReached                           = 'Se llegó al inicio de la tabla y no se encontraron registros coincidentes.';
  sPSCSearchFromBegin                           = ' Desea continuar la búsqueda desde el inicio de la tabla?';
  sPSCSearchFromEnd                             = ' Desea continuar la búsqueda desde el final de la tabla?';
  SPSCSpecifyFilter                             = 'Especifique el filtro';
  SPSCFilterLabel                               = '&Filtro:';
  SPSCExcludeFilterLabel                        = '&Excluir filtro:';
  SPSCCap_OnDate                                = 'es ~la fecha~';
  SPSCBadFieldType                              = 'Tipo de campo erróneo';
  SPSCErrDataSetNilNoFields                     = 'DataSet en NIL y propiedad Fields no especificada';
  SPSCErrNoFields                               = 'Propiedad Fields no está especificada';


// Error messages
SPSCInvalidColor='''%s'' es un valor de color no válido';
SPSCInvalidClass='No se puede aceptar ''%s''';

// Color names
SPSCBlack='Negro';
SPSCBrown='Café';
SPSCOliveGreen='Verde Oliva';
SPSCDarkGreen='Verde Oscuro';
SPSCDarkTeal='Aguamarina Oscuro';
SPSCDarkBlue='Azul Oscuro';
SPSCIndigo='Indigo';
SPSCGray80='Gris-80%';
SPSCDarkRed='Rojo Oscuro';
SPSCOrange='Naranja';
SPSCDarkYellow='Amarillo Oscuro';
SPSCGreen='Verde';
SPSCTeal='Aguamarina';
SPSCBlue='Azul';
SPSCBlueGray='Azul-Gris';
SPSCGray50='Gris-50%';
SPSCRed='Rojo';
SPSCLightOrange='Naranja Claro';
SPSCLime='Lima';
SPSCSeaGreen='Verde Mar';
SPSCAqua='Agua';
SPSCLightBlue='Azul claro';
SPSCViolet='Violeta';
SPSCGray40='Gris-40%';
SPSCPink='Rosado';
SPSCGold='Oro';
SPSCYellow='Amarillo';
SPSCBrightGreen='Verde Brillante';
SPSCTurquoise='Turquesa';
SPSCSkyBlue='Azul Cielo';
SPSCPlum='Plomo';
SPSCGray25='Gris-25%';
SPSCRose='Rosa';
SPSCTan='Canela';
SPSCLightYellow='Amarillo Claro';
SPSCLightGreen='Verde Claro';
SPSCLightTurquoise='Turquesa Claro';
SPSCPaleBlue='Azul Pálido';
SPSCLavender='Lavanda';
SPSCWhite='Blanco';

// New system color names
SPSCHotLight='Luz Cálida';
SPSCGradientActiveCaption='Gradiente de Título Activo';
SPSCGradientInactiveCaption='Gradiente de Título Inactivo';
SPSCTransparent='Color Transparente';

// Captions
SPSCMoreColorsCapt='&Más colores...';
SPSCMoreColors='Más colores';
SPSCAuto='Automático';
SPSCAutoColor='Color Automático';
SPSCNone='Ninguno';
SPSCNoHighLight='Sin Resaltar';
SPSCStdColors='&Colores Estándar:';
SPSCWindowsColors='Colores de &Windows:';
SPSCDocColors='Colores del &Documento:';
SPSCFontColors='Colores de &Fuente:';
SPSCCustomColors='Colores &Personalizados:';
SPSCCustomColorsCapt='Colores Personalizados';

// Items
SPSCAddSlot='Adicionar ranura';
SPSCDeleteSlot='Eliminar ranura';

// Sections
SPSCDefaultSection='Sección por Defecto';
SPSCColorSection='Sección de Color';
SPSCButtonSection='Sección de Botón';

// Popup window
SPSCDragBarHint='Arrastre para hacer este flotante este menú';

  SPSCErrCharSetDef='Definición de juego de caractéres inválido';
  SPSCErrMaxIfDefReached='Sólo %d niveles encadenados de directivas del compilador están permitidos';
  SPSCErrCompilerDirective='Directiva inválida del compilador: "%s"';
  SPSCErrFileNotFound='Archivo %S no encontrado';
  sPSCDirectory  = 'Directorio :  ';
  SPSCNotProcessedfiles = 'Archivos no procesados:';
  SPSCErrStringsNotSet = 'Las cadenas no han sido especificadas';

//------------------ Not yet localized

  SPSCErrProgramFailed='Error de programa con código (%d)';
  SPSCCharExpected = '''''%s'''' era esperado';
  SPSCSymbolExpected = '%s era esperado';
  SPSCErrUnkProp = 'La propiedad no existe';
  SPSCErrLoadFile = 'No se puede cargar %s';


  SPSCErrAssignFilterSource='Asigne la propiedad FilterSource con TPSCFltBld';
  SPSCErrConnectDataSet='Conecte el TDataSet o especifíque la propiedad Fields';
  SPSCErrNoFilterSource='FilterSource no está asignado';
  SPSCErrCanNotDestroy='No se puede destruir este objeto';
  SPSCErrBadPropElem = 'Elemento inválido en la propiedad: %s';
  SPSCThereAreNoItems='No hay items para mostrar en esta vista';
  SPSCClickHeretoChangeSortOrder='Pulsar aquí para cambiar el ordenamiento';
  SPSCSortAscending='Ordenar Ascendentemente';
  SPSCSortDescending='Ordenar Descendentemente';
  SPSCClearSortOrder='Limpiar el ordenamiento';
  SPSCIgnoreCase='&Ignorar mayúsculas/minúsculas';
  SPSCClickHereToAddValue='<Pulsar aquí para adicionar valor>';
  SPSCCap_In='en';
  SPSCCap_NotIn='no en';
  SPSCAddAllFields='Adicionar Todos los Campos';
  SPSCAddAllFieldParams='Adicionar Todos los FieldParams';
  SPSCFindFirst='Buscar el Primero';
  SPSCFindPrev='Buscar el Anterior';
  SPSCFindNext='Buscar el Siguiente';
  SPSCFindLast='Buscar el Ultimo';
  SPSCColorIndicatedCells='Color indicated cell(s)';
  SPSCFiltered='Filtrado';
  SPSCErrHandlerAlreadyExists='El Handler ya existe';
  SPSCErrHandlerNotExists='El Handler no existe';
  SPSCApplyChanges='Aplicar cambios';
  SPSCCancelChanges='Ignorar cambios';
  SPSCErrDupItem = 'No se puede insertar un item duplicado';

  SPSCAdditionalFilter='[Filtro Adicional]';
  SPSCAutoUpdate='Actualizar Automáticamente';

  SPSCAssignError                            = 'No se puede asignar un %s a un %s';
  SPSCOKButton                               = 'OK';
  SPSCCancelButton                           = 'Cancelar';
  SPSCHelpButton                             = '&Ayuda';
  SPSCReadError                              = 'Error leyendo el Stream';
  SPSCWriteError                             = 'Error escribiendo el Stream';

  SPSCErrRefCount='El contador de referencias del objeto es diferente de cero';
  SPSCExceptionIn='Excepción en %S';
  SPSCErrInvalidfieldkind='Tipo de campo inválido';
  SPSCOperationDispAndNot                    = 'y no';
  SPSCOperationDispOrNot                     = 'o no';
