  Caption:= MsgCaption(560);

  labAvail.Caption:= MsgCaption(561);
  labCurrent.Caption:= MsgCaption(562);

  btnAdd.Caption:= MsgCaption(563);
  btnRemove.Caption:= MsgCaption(564);
  btnOK.Caption:= MsgCaption(350);
  btnCancel.Caption:= MsgCaption(351);
  btnReset.Caption:= MsgCaption(565);
  btnUp.Caption:= MsgCaption(505);
  btnDown.Caption:= MsgCaption(506);

  sMsgButtonSeparator:= MsgCaption(566);


