  Caption:= MsgCaption(880);
  btnClose.Caption:= MsgCaption(353);

  List.Columns[0].Caption:= MsgCaption(883);
  List.Columns[1].Caption:= MsgCaption(884);
  List.Columns[2].Caption:= MsgCaption(885);

  tc.Tabs.Strings[0]:= MsgCaption(890);
  tc.Tabs.Strings[1]:= MsgCaption(891);
  tc.Tabs.Strings[2]:= MsgCaption(892);
  tc.Tabs.Strings[3]:= MsgCaption(893);
  tc.Tabs.Strings[4]:= MsgCaption(894);
  tc.Tabs.Strings[5]:= MsgCaption(895);

  //Messages
  MsgViewerExifMissed:= MsgString(126);
