  //Captions
  Caption:= MsgCaption(500);
  boxPlugins.Caption:= ' ' + MsgCaption(501) + ' ';
  boxOptions.Caption:= ' ' + MsgCaption(280) + ' ';

  btnAdd.Caption:= MsgCaption(502);
  btnRemove.Caption:= MsgCaption(503);
  btnConfig.Caption:= MsgCaption(507);
  btnUp.Caption:= MsgCaption(505);
  btnDown.Caption:= MsgCaption(506);

  List.Columns[0].Caption:= MsgCaption(510);
  List.Columns[1].Caption:= MsgCaption(511);
  List.Columns[2].Caption:= MsgCaption(512);

  chkPriority.Caption:= MsgCaption(520);
  chkTCVar.Caption:= MsgCaption(521);
  chkHideKeys.Caption:= MsgCaption(524);

  btnOK.Caption:= MsgCaption(350);
  btnCancel.Caption:= MsgCaption(351);
  btnHelp.Caption:= MsgCaption(155);

  //Messages
  MsgViewerPluginsInstalled:= MsgString(210);
  MsgViewerPluginsInstalledZip:= MsgString(209);
  MsgViewerPluginsNone:= MsgString(211);
  MsgViewerPluginsInvalidFile:= MsgString(212);
  MsgViewerPluginsInvalidTCExe:= MsgString(213);
