  {$ifdef PREVIEW}

  MsgPreviewDlgCaption:= MsgCaption(720);
  MsgPreviewDlgPrint:= MsgCaption(721);
  MsgPreviewDlgPrintSetup:= MsgCaption(736);
  MsgPreviewDlgCancel:= MsgCaption(351);

  MsgPreviewDlgOptions:= ' ' + MsgCaption(722) + ' ';
  MsgPreviewDlgPosition:= ' ' + MsgCaption(726) + ' ';
  MsgPreviewDlgPreview:= ' ' + MsgCaption(723) + ' ';
  MsgPreviewDlgMargins:= ' ' + MsgCaption(710) + ' ';
  MsgPreviewDlgGamma:= ' ' + MsgCaption(718) + ' ';

  MsgPreviewDlgMarginLeft:= MsgCaption(711);
  MsgPreviewDlgMarginTop:= MsgCaption(713);
  MsgPreviewDlgMarginRight:= MsgCaption(712);
  MsgPreviewDlgMarginBottom:= MsgCaption(714);

  MsgPreviewDlgOptFitMode:= MsgCaption(727);
  MsgPreviewDlgOptFitSizeX:= MsgCaption(733);
  MsgPreviewDlgOptFitSizeY:= MsgCaption(732);
  MsgPreviewDlgOptFitSizeProp:= MsgCaption(734);
  MsgPreviewDlgOptFooter:= MsgCaption(724);
  MsgPreviewDlgOptFooterFont:= MsgCaption(735);
  MsgPreviewDlgOptGamma:= MsgCaption(719);

  MsgPreviewDlgUnit[pUnitMm]:= MsgCaption(715);
  MsgPreviewDlgUnit[pUnitCm]:= MsgCaption(716);
  MsgPreviewDlgUnit[pUnitIn]:= MsgCaption(717);

  MsgPreviewDlgFitModes[pFitNormal]:= MsgCaption(728);
  MsgPreviewDlgFitModes[pFitBest]:= MsgCaption(729);
  MsgPreviewDlgFitModes[pFitStretch]:= MsgCaption(730);
  MsgPreviewDlgFitModes[pFitSize]:= MsgCaption(731);

  MsgPreviewDlgCannotAllocateMemory:= MsgCaption(725);

  {$endif}
