  Caption:= MsgCaption(601);

  GroupBox1.Caption:= ' ' + MsgCaption(601) + ' ';
  OpenDialog1.Filter:= MsgCaption(541);

  labCaption.Caption:= MsgCaption(602);
  labCommand.Caption:= MsgCaption(603);
  labParams.Caption:= MsgCaption(604);
  labParamsHint.Caption:= MsgCaption(609);
  labMacros.Caption:= MsgCaption(605);
  labActions.Caption:= MsgCaption(606);
  labActions1.Caption:= MsgCaption(607);
  labActions2.Caption:= MsgCaption(608);

  chkSelectAll.Caption:= MsgCaption(123);
  chkCopy.Caption:= MsgCaption(122);
  chkExit.Caption:= MsgCaption(119);

  btnOK.Caption:= MsgCaption(350);
  btnCancel.Caption:= MsgCaption(351);
