const //Exception messages
  sfbeOtherError        = 'Другая ошибка';
  sfbeCircularReference = 'Циклическая ссылка компонент запрещена (%s).'; //fbeCircularReference
  sfbeEmptySQLEdit      = 'Пустой текст SQL запроса редактирования (%s).'; //sfbeEmptySQLEdit
  sfbeDatabaseNotAssigned = 'Свойство Database не присвоено (%s)';
  sfbeTransactionNotAssigned = 'Свойство Transaction не присвоено (%s)';
  sfbeParameterNotFound = 'Параметр не найден (%s)';
  sfbeNotCachedUpdates  = 'Не включен ражим кэширования (%s)';
  sfbeUserAbort = 'Отменено пользователем';
  sfbeErrorExecuteQ       = 'Ошибка выполнения запроса %s (%s).';
  sfbeBlobCannotBeWritten = 'Blob поток не может быть записан.';
  sfbeGetRecordInvalidRec = 'GetRecord: Ошибка поиска записи';

  EReferencedRecordBufferLooseMsg = 'Попытка освободить не существующий буфер данных';
  EReferencedDatSetRecordBufferLooseMsg = 'Попытка освободить не существующий буфер набора данных';
  EReferencedBLOBCacheLooseMsg    = 'TBLOBCache:попытка освободить используемый буфер данных';

const //Localizations
  slcOk     = 'OK';
  slcCancel = 'Отмена';
  slcHelp   = 'Помощь';
  //Auto update options window
  slcUpdatedField  = 'Изменяемое поле';
  slcGeneratorName = 'Генератор';
  slcIncrementBy   = 'Приращение';
