//--------------------------------------------------------------------------------
// ATViewer options:
//
// TNT           Use Tnt Unicode Controls library.
// GEX           Use GraphicEx library.
// GIF           Use GIFImage library.
// PNG           Use PNGImage library.
// IJL           Use IJL library.
// JP2           Use Jpeg2000 library.
// ANI           Use AmnAni library (dll).
// TIFF          Use LibTiff library (dll).
// PREVIEW       Use ATPrintPreview unit.
// IVIEW         Use nmzIrfanXnView unit (included).
//
// MEDIA_PLAYER  Enable MCI media mode. This links winmm.dll.
// MEDIA_WMP64   Enable Windows Media Player 6.4 media mode.
// MEDIA_WMP9    Enable Windows Media Player 9.x media mode.
//
// WLX           Enable plugins mode.
// WLX_FORM      Enable helper "Total Commander [fake window]" hidden form.
// WLX_UNLOAD    Enable plugins unloading on closing.
//               This causes AV with some plugins: Syn, Hpg_Ed, IniEd.
// IE4X          Enable usage of WebBrowser4_TLB unit.
//               See desc. of WebAcceptAllFiles property.
// NOTIF         Enable file change notification code.
// PRINT         Enable printing code.
// SEARCH        Enable searching code.
// OFFLINE       Enable WebOffline property usage.
//
//--------------------------------------------------------------------------------

//{$define TNT}
//{$define GEX}
//{$define GIF}
//{$define PNG}
//{$define IJL}
//{$define JP2}
//{$define ANI}
//{$define PREVIEW}
//{$define IVIEW}

{$define MEDIA_PLAYER}
{$define MEDIA_WMP64}
{$define MEDIA_WMP9}

{$define WLX}
//{$define WLX_FORM}
//{$define WLX_UNLOAD}

//{$define IE4X}
{$define NOTIF}
{$define PRINT}
{$define SEARCH}
{$define OFFLINE}
