CREATE TABLE CUSTOMER
(
   CUSTNO     NUMBER        NOT NULL,
   COMPANY    VARCHAR2(30)  NOT NULL
);

CREATE TABLE ORDERS
(
   ORDERNO     NUMBER       NOT NULL,
   CUSTNO      NUMBER       NOT NULL,
   SALEDATE    DATE         NOT NULL,
   SHIPDATE    DATE         NOT NULL,
   EMPNO       NUMBER(9)    NOT NULL
);

CREATE TABLE ITEMS
(
   ORDERNO    NUMBER        NOT NULL,
   ITEMNO     NUMBER        NOT NULL,
   PARTNO     NUMBER        NOT NULL,
   QTY        NUMBER        NOT NULL,
   DISCOUNT   NUMBER(9)     NOT NULL
);
